server:
  port: 8080

jwt:
  secret: dzfgh869gdhy6zgd9jhdej
  lifetime: 10m

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mydb
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: false